language: c++

sudo: enabled

dist: trusty

os:
  - linux

addons:
  apt:
    packages:
      - gfortran 
      - libboost-all-dev
      - libhdf5-dev

compiler:
  - gcc

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/hdf5/serial
  - sh travis/install-SAMRAI.sh
