language: c++

sudo: enabled

dist: trusty

os:
  - linux

addons:
  apt:
    packages:
      - gfortran 
      - libboost-all-dev
      - libhdf5-serial-dev

compiler:
  - gcc

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - mkdir hdf5
  - cd hdf5
  - ln -s include /usr/include/hdf5/serial/
  - ln -s lib /usr/lib/x86_64-linux-gnu/hdf5/serial/
  - cd ..
  - sh travis/install-SAMRAI.sh
