language: c++

sudo: enabled

dist: trusty

os:
  - linux

addons:
  apt:
    packages:
      - gfortran 
      - libboost-all-dev

compiler:
  - gcc

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - sh travis/install-hdf5.sh
  - sh travis/install-SAMRAI.sh

install:
  - mkdir build
  - cd build
  - cmake ..
