language: c++

sudo: enabled

dist: trusty

os:
  - linux

addons:
  apt:
    packages:
        - libboost-all-dev
        - libhdf5-serial-dev

compiler:
  - gcc

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - sh pipeline/install-openMPI.sh
