pipelines:
  branches:
    master: &default-step
      - step:
          script:
            # Install deps.
            - apt-get update && apt-get install -y libboost-all-dev libhdf5-serial-dev
            - source pipeline/install-openMPI.sh